Import('*')

SimObject('SparTA.py', sim_objects=[
    'PE_Mul',
    'PE_Acc',
    'MatMul',
    'BaselineDriverSequential',
    'BaselineDriverParallel',
    'AcceleratorDriver',
    'AcceleratorDriverSPADA',
    'BlockSPADADriver',
    'GammaDriver'
])

Source('PE_Mul.cc')
Source('PE_Acc.cc')
Source('MatMul.cc')
Source('baseline/sequential/BaselineDriverSequential.cc')
Source('baseline/parallel/BaselineDriverParallel.cc')
Source('accelerator/AcceleratorDriver.cc')
Source('baseline/spada/AcceleratorDriverSPADA.cc')
Source('baseline/block-spada/BlockSPADADriver.cc')
Source('baseline/gamma/GammaDriver.cc')
