Import('*')

SimObject('SparTA.py', sim_objects=[
    'PE_Mul',
    'PE_Acc',
    'MatMul',
    'BaselineDriverSequential',
    'BaselineDriverParallel',
    'AcceleratorDriver',
    'GammaDriver',
    'PadeDriver',
    'SpMardDriver'
])

Source('PE_Mul.cc')
Source('PE_Acc.cc')
Source('MatMul.cc')
Source('baseline/sequential/BaselineDriverSequential.cc')
Source('baseline/parallel/BaselineDriverParallel.cc')
Source('accelerator/AcceleratorDriver.cc')
Source('baseline/gamma/GammaDriver.cc')
Source('baseline/pade/PadeDriver.cc')
Source('baseline/spmard/SpMardDriver.cc')
